### PR TITLE
Almost compatible with dribbble's new API

### PR DESCRIPTION
**Pull request by jonastaedcke**
I added the Access Token and edited the 9 of 11 methods.

### CODE REVIEW

**Comment by martinbean** [comment]
Thanks, @jonaszielke, but I don’t want to break backwards compatibility with making a default access token value being supplied (`XXX`).

I did make a start on a new version of this library to use the latest Dribbble API version, but haven’t had chance to finish it yet.

**Comment by martinbean** [comment]
@jonaszielke If you want to use Dribbble’s new API, then I’ve just pushed [version 4](https://github.com/martinbean/dribbble-php/releases/tag/v4.0.0) of this library.

**Comment by jonastaedcke** [comment]
Thank you, @martinbean! Looks great!

**Comment by martinbean** [comment]
@jonaszielke I still need to add support for parameters, build should be enough to get people up and running.

**Pull request closed without merging**
